#!/usr/bin/env ruby
# frozen_string_literal: true

## Copyright 2024 Dan Higgins
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #     http://www.apache.org/licenses/LICENSE-2.0
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.

[['zeitwerk', '~> 2.0']].each do |args|
  begin
    gem(*args[0..1])
    require(args[2] || args[0]) if args[2] != false
  rescue Exception => e
    puts "#{e.class}: #{e.message}:\n\nPlease run: gem install #{args[0]} -v '#{args[1]}'"
    exit 1
  end
end

Zeitwerk::Loader.new.tap do |loader|
  $EXE_DIR = __dir__
  loader.push_dir(File.join($EXE_DIR, "lib"))
  loader.setup
end

exit(Dmis::Sudoku::Cli.new(ARGV).run) if $0 == __FILE__
